"area: gradle":
  - build.gradle.kts
  - gradlew.bat
  - gradlew
  - gradle.properties
  - gradle/*
"area: repo":
  - ./*
# PRs about instructions or the StackFrame.
"area: bytecode":
  # Double ** because I'm lazy.
  - src/**/UserCodeStackFrame.kt
  - src/**/instruction/*
# PRs about the interpreter
"area: builtins":
  - src/**/interpreter/pyobject/*
  - src/**/interpreter/pyobject/**/*
