"area: gradle":
  - build.gradle.kts
  - gradlew.bat
  - gradlew
  - gradle.properties
  - gradle/*
  - annotations/build.gradle.kts
  - generators/build.gradle.kts
  - core/build.gradle.kts
"area: repo":
  - ./*
# PRs about instructions or the StackFrame.
"area: bytecode":
  # Double ** because I'm lazy.
  - core/src/**/UserCodeStackFrame.kt
  - core/src/**/instruction/*
# PRs about the interpreter
"area: builtins":
  - core/src/**/interpreter/pyobject/*
  - core/src/**/interpreter/pyobject/**/*
