name: Gradle Build - Test - Dist

on:
  push:
    branches:
      - master
      - "3.*"

  pull_request: {}

jobs:
  test:
    runs-on: ${{ matrix.run_on }}
    strategy:
      matrix:
        # needs updates as appropriate
        java: [11.0.x, 13]
        run_on: [windows-latest, ubuntu-latest, macos-latest]


      # prevents different java version tests failing
      fail-fast: false

    steps:
    - uses: actions/checkout@v1

    - name: Set up Java ${{ matrix.java }}
      uses: actions/setup-java@v1
      with:
        java-version: ${{ matrix.java }}

    - name: Install CPython 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8.0
        architecture: x64

    - name: Make sure gradle is executable
      run: chmod +x ./gradlew

    - name: Run gradle dependencies
      run: ./gradlew dependencies

    - name: Run tests
      run: ./gradlew build test jacocoTestReport

    - name: Upload coverage
      uses: codecov/codecov-action@v1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        file: build/reports/jacoco/test/jacocoTestReport.xml
        name: kython-java-${{ matrix.java }}

    - name: Build distribution
      run: ./gradlew distZip

    - name: Upload reports
      uses: actions/upload-artifact@v1
      if: always()
      with:
        name: Reports
        path: build/reports

    - name: Upload build files
      uses: actions/upload-artifact@v1
      with:
        name: Distributions
        path: build/distributions
